export enum EnviromentVariablesEnum {
    PORT = 'PORT',
    JWT_SECRET_KEY = 'JWT_SECRET_KEY',
    JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',
    JWT_FRONTEND_ENCRYPTION_KEY = 'JWT_FRONTEND_ENCRYPTION_KEY',
    ENABLE_CORS = 'ENABLE_CORS',
    ENABLE_DOCS = 'ENABLE_DOCS',
    APP_VERSION = 'APP_VERSION',
    NODE_ENV = 'NODE_ENV',
    NOSQL_CONNECTION_STRING = 'NOSQL_CONNECTION_STRING',
}
